apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: cve-policy
spec:
  images:
  - glob: "**"
  authorities:
  - keyless:
      identities:
      - issuer: https://token.actions.githubusercontent.com
        subject: https://github.com/knabben/dos-poc/.github/workflows/sign.yml@refs/heads/main
    attestations:
    - name: blockcve
      predicateType: "https://cyclonedx.org/bom"
      policy:
        type: cue
        data: |
          import "strings"

          cve: "CVE-2023-39325"
            
          predicate: {
            vulnerabilities: [...]
            error: strings.Join([ 
              for v in vulnerabilities 
                if v.id == cve {
                  "**" + cve + "** encountered in the image."
                } 
            ], "")
          }
          predicate: error: ""
