apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: cve-policy
spec:
  images:
  - glob: "**"
  authorities:
  - keyless:
      identities:
      - issuer: https://token.actions.githubusercontent.com
        subject: https://github.com/knabben/dos-poc/.github/workflows/sign.yml@refs/heads/main
    attestations:
    - name: musthave
      predicateType: "https://cyclonedx.org/bom"
      policy:
        type: cue
        data: |
          import "encoding/json"
          import "strings"
          import "list"

          #Predicate: {
            Data: string
            Timestamp: string
          }

          cveList: [ "CVE-2023-39325" ]

          predicate: {
            vulnerabilities: [...]
            result: [ for v in vulnerabilities if list.Contains(cveList, v.id) {v.id} ]
            ...
          }

          predicate: result: list.MaxItems(0)
