apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: oci-dospoc
  namespace: flux-system
spec:
  interval: 5m0s
  provider: generic
  ref:
    semver: ">=0.0.1"
  url: oci://ttl.sh/knabben/manifests/dos-poc
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-dospoc
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: OCIRepository
    name: oci-dospoc
  targetNamespace: default
  timeout: 3m0s
  wait: true
