---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: dos-poc
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    digest: sha256:1d6093c3257ba546f1c5265abb263da3f6a028accdc81040f7736ff2d1200129
  url: oci://ttl.sh/knabben/manifests/dos-poc
