---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: dos-poc
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: 0.0.1
  url: oci://ttl.sh/knabben/manifests/dos-poc
